### ISSUE TITLE
please add another native application resolution

### ISSUE THREAD

**Issue by best3140** [ds5qdr/USRP-for-Raspberrypi#2]
Dear DS5QDR

     please add another native application resolution for like 240x320, 320x480 or other
that can native resolution fit for tft 2.8, 3.2 or 3.5 inch display for raspberry pi
     maybe it will reduce resource usage when run on raspberry pi zero.

Best Regards,
E25ECY

**Comment by ds5qdr** [comment]
i tested 3.5", 5", 7" LCD at resolution 800 x 480,
but not tested 2.8" and 3.2"

**Comment by ds5qdr** [comment]
closed
