### ISSUE TITLE
Default Sound card can not start

### ISSUE THREAD

**Issue by best3140** [ds5qdr/USRP-for-Raspberrypi#3]
i start software from ./usrp_start and get error message below. i test sound card can play sound normal.

/tmp/_MEIGOuwcu/pysftp/__init__.py:61: UserWarning: Failed to load HostKeys from /home/pi/.ssh/known_hosts.  You will need to explicitly load HostKeys (cnopts.hostkeys.load(filename)) or disableHostKey checking (cnopts.hostkeys = None).
Invalid card number.
Invalid card number.
Traceback (most recent call last):
  File "USRP.py", line 5366, in <module>
  File "USRP.py", line 2640, in rpi_volume
ValueError: invalid literal for int() with base 10: "Usage: amixer <options> [command]\n\nAvailable options:\n  -h,--help       this help\n  -c,--card N     select the card\n  -D,--device N   select the device, default 'default'\n  -d,--debug      debu
[711] Failed to execute script USRP

**Comment by ds5qdr** [comment]
see below 
https://github.com/ds5qdr/USRP_update
reinstall usrp again
if error occur pls feedback the returns after comment : aplay -l 
ex]
**** List of PLAYBACK Hardware Devices ****
card 0: b1 [bcm2835 HDMI 1], device 0: bcm2835 HDMI 1 [bcm2835 HDMI 1]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 1: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 4/4
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
card 2: Set [C-Media USB Headphone Set], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

nomally, there are two types : Speaker or Headphone I know
the others I don't know!

pls F/Back 'aplay -l'

**Comment by ds5qdr** [comment]
I fixed the error you mentioned.
pls goto https://github.com/ds5qdr/USRP_update
and download or reinstall USRP
Thanks

**Comment by best3140** [comment]
many thanks. i will test and report back as soon as possible.

**Comment by best3140** [comment]
still have same error
pi@dvpi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@dvpi:~ $
pi@dvpi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Device [USB Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@dvpi:~ $
pi@dvpi:~ $ speaker-test 

speaker-test 1.1.8

Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 96 to 262144
Period size range from 48 to 131072
Using max buffer size 262144
Periods = 4
was set period_size = 65536
was set buffer_size = 262144
 0 - Front Left
Time per period = 2.768053
 0 - Front Left
Time per period = 2.771798
 0 - Front Left
Time per period = 2.775857
 0 - Front Left
Time per period = 2.775811
 0 - Front Left
Time per period = 2.769754
 0 - Front Left
Time per period = 2.773746
 0 - Front Left
Time per period = 2.775814
 0 - Front Left
Time per period = 2.775729
 0 - Front Left
^CTime per period = 1.186967
pi@dvpi:~ $

**Comment by best3140** [comment]
![image](https://user-images.githubusercontent.com/26781774/125446963-a910c547-bb30-4d52-ba5d-7654919b043d.png)

**Comment by ds5qdr** [comment]
download below files
https://drive.google.com/file/d/1qF1p-EOkHIg-5QYZle2EX2cG0IQZUKCV/view?usp=sharing
there are two version
USRP_1 is V2.59
USRP_2 is V2.59 but without alsamixer control if error occur

i tested two kinds of sound card so i don't know whether your sound card operate or now.
thanks

**Comment by best3140** [comment]
USRP_2 are working event it show many line of " invalid card number "

**Comment by ds5qdr** [comment]
closed

**Comment by ds5qdr** [comment]
closed
