### ISSUE TITLE
SDCard iso

### ISSUE THREAD

**Issue by PD1LOI** [ds5qdr/USRP-for-Raspberrypi#4]
Will there also be a complete iso file that can be placed directly on an SDCard?

**Comment by ds5qdr** [comment]
end of this weekend i will upload image file!

Thanks.


________________________________
From: L Kuperij ***@***.***>
Sent: Thursday, November 11, 2021 6:15:31 PM
To: ds5qdr/USRP-for-Raspberrypi ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ds5qdr/USRP-for-Raspberrypi] SDCard iso (Issue #4)


Will there also be a complete iso file that can be placed directly on an SDCard?

**Comment by ds5qdr** [comment]
Uploaded full image file USRP_V3.1x.img 
use Win32DiskImager or other image maker program to write your 16G SD card for RPi
Thanks

**Comment by ds5qdr** [comment]
closed
