### ISSUE TITLE
svxlink and USRP

### ISSUE THREAD

**Issue by lordkane** [ds5qdr/USRP-for-Raspberrypi#6]
Hello please help me i want connect usrp with svxlink.
wenn someone speak usrp go to svxlink ...
wenn someone speak svxlink go to usrp.

i have install snd-aloop but usrp does not found it.

**Comment by ds5qdr** [comment]
I can access to svxlink as follow
USRP <-> YSF(DMR) <-> ASL <-> ASL Echolink <-> SVXlink
the other way I have no information about what you comments.

**Comment by lordkane** [comment]
can you help me to install ?

**Comment by lordkane** [comment]
.) Basic structure

               |.-................. SvxLink ......................|   |........... MMDVM stuff ..........|   |.. freeDMR ..>

|----------|   |---------------|   |--------------|   |-----------|   |---------------|   |--------------|   |-------------|
|  Radio   |   | SimplexLogic  |   | LogicLinking |   | UsrpLogic |   | Analog_Bridge |   | MMDVM_Bridge |   | DMR-Network |
|  2m/70cm |<->| RepeaterLogic |<->|              |<->|           |<->|               |<->|              |<->|             |
|----------|   |---------------|   |--------------|   |-----------|   |---------------|   |--------------|   |-------------|
                                           |                                  |
                                           |                                  |
|----------|   |---------------|   |--------------|                   |---------------|
| Analogue |   | SvxReflector- |   | Reflector-   |                   | md380-        |
| Network  |<->|    Server     |<->| Logic        |                   | emulator      |
|----------|   |---------------|   |--------------|                   |---------------|

**Comment by lordkane** [comment]
i want only USRP <-> SVXlink
with md380 emu...

**Comment by ds5qdr** [comment]
It would be better to inquire about the concept you want at the link below
https://dvswitch.groups.io/g/main/topics

**Comment by lordkane** [comment]
i have install dvswitch server from windows with your version work it fine...
but svxlink and usrp not :(

**Comment by ds5qdr** [comment]
closed
